__title__ = 'aiologin'
__description__ = 'User session management for aiohttp'
__url__ = 'https://github.com/trivigy/aiologin'
__version_info__ = ('0', '0', '1')
__version__ = '.'.join(__version_info__)
__author__ = 'Konstantin Itskov'
__author_email__ = 'konstantin.itskov@kovits.com'
__license__ = 'MIT'
__copyright__ = '(c) 2016 by Konstantin Itskov'
